apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-end-deploy
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: front-end
  template:
    metadata:
      labels:
        app: front-end
    spec:
      containers:
      - name: front-end-deploy
        image: public.ecr.aws/w8w9x8q7/front-end:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
           
---
apiVersion: v1
kind: Service
metadata:
  name: "front-end-service"
spec:
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
  type: LoadBalancer
  selector:
    app: front-end
